#!/usr/bin/env php
<?php

/*
 * This file is part of CLI Press.
 *
 * The MIT License (MIT)
 * Copyright © 2017
 *
 * Alex Carter, alex@blazeworx.comf
 * Keith E. Freeman, cli-press@forsaken-threads.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that should have been distributed with this source code.
 */

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application as Commander;

$app = app();
$app->bootstrap(getcwd(), __DIR__);

$commander = $app->make(Commander::class);

// there's no point in adding all commands unless we actually have to, i.e. list command was given
if (empty($argv[1]) || $argv[1] == 'list' || ! ($command = $app->labeled('command.' . strtolower(@(string) $argv[1])))) {
    $commander->addCommands($app->tagged('command'));
} else {
    // Register the command being run with the commander and the application
    $commander->add($command);
    $app['command.current'] = strtolower(@(string) $argv[1]);
}

define('CLI_PRESS', __FILE__);

$commander->run();