<?php

/*
 * This file is part of CLI Press.
 *
 * The MIT License (MIT)
 * Copyright © 2017
 *
 * Alex Carter, alex@blazeworx.com
 * Keith E. Freeman, cli-press@forsaken-threads.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that should have been distributed with this source code.
 */

namespace BlazingThreads\CliPress\Commands;

use BlazingThreads\CliPress\Managers\TemplateManager;
use mikehaertl\wkhtmlto\Pdf;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class Generate extends Command
{

    protected $config;

    /**
     * @var \ParsedownExtra
     */
    protected $parseDown;

    /**
     * @var TemplateManager
     */
    protected $templateManager;

    protected function configure()
    {
        $this
            ->setName('generate')
            ->setDescription('Start up the press and make something beautiful');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->templateManager = app()->make('managers.template');
        $this->parseDown = new \ParsedownExtra();
        $this->config = [
            'theme' => 'cli-press',
            'title' => 'Generated by CLI Press',
        ];

        if (file_exists('cli-press.json')) {
            $json = json_decode(file_get_contents('cli-press.json'), true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $this->config = array_merge($this->config, $json);
            }
        }

        if (empty($this->config['filename'])) {
            $this->config['filename'] = preg_replace('/[^\w\._-]/', '-', $this->config['title']);
        }

        if (!empty($this->config['theme'])) {
            if ($this->config['theme'] == 'cli-press' || !file_exists(dirname($this->getThemePath('file', $this->config['theme'])))) {
                $this->config['theme'] = false;
            }
        }

        $output->writeln('<comment>Starting the press</comment>');

        $pdf = new Pdf();

        $coverPageHtml = $this->generateCoverPageHtml();

        if ($coverPageHtml) {
            file_put_contents('cli-press_cover.html', $coverPageHtml);
            $pdf->addCover('cli-press_cover.html');
            $this->config['hasCover'] = true;
        }

        $pdf->setOptions([
            'header-html' => 'cli-press_header.html',
            'footer-html' => 'cli-press_footer.html',
        ]);

        $headerHtml = $this->generateHeaderHtml($this->config['title']);

        $bodyHtml = $this->generateBodyHtml(glob('*.md'));

        $footerHtml = $this->generateFooterHtml();

        file_put_contents('cli-press_header.html', $headerHtml);
        file_put_contents('cli-press_body.html', $bodyHtml);
        file_put_contents('cli-press_footer.html', $footerHtml);

        $pdf->addToc([
            'xsl-style-sheet' => $this->getToc()
        ]);

        $pdf->addPage('cli-press_body.html');

        if (!$pdf->saveAs($this->config['filename'] . '.pdf')) {
            $output->write('<fg=red>ERROR:</fg=red> ' . $pdf->getError());
        } else {
            $output->write("<info>Complete!</info>\n");
        }

        exec('rm cli-press_*.html');
    }

    private function generateCoverPageHtml() {
        if (!file_exists('cover.md')) {
            return '';
        }
        $coverContent = $this->parseDown->parse(file_get_contents('cover.md'));
        $coverContent = $this->faParse($coverContent, $withFA);
        $baseCss = $this->getThemeFile('cover.css', [], true);
        $themeCss = $this->getThemeFile('cover.css');
        $now = date('Y-m-d H:i:s');
        $cover = $this->getFirstFile('cover.twig', compact('coverContent', 'now'));
        return $this->getFirstFile('cover-layout.twig', compact('baseCss', 'themeCss', 'cover', 'withFA'));
    }

    private function generateHeaderHtml($title) {
        $baseCss = $this->getThemeFile('header.css', [], true);
        $themeCss = $this->getThemeFile('header.css');
        $header = $this->parseDown->parse($this->getFirstFile('header.twig', compact('title')));
        $header = $this->faParse($header, $withFA);
        return $this->getFirstFile('header-layout.twig', compact('baseCss', 'themeCss', 'header', 'withFA'));
    }

    private function generateFooterHtml() {
        $baseCss = $this->getThemeFile('footer.css', [], true);
        $themeCss = $this->getThemeFile('footer.css');
        $footer = $this->parseDown->parse($this->getFirstFile('footer.twig'));
        $footer = $this->faParse($footer, $withFA);
        return $this->getFirstFile('footer-layout.twig', compact('baseCss', 'themeCss', 'footer', 'withFA'));
    }

    private function generateBodyHtml($files) {
        $baseCss = $this->getThemeFile('body.css', [], true);
        $themeCss = $this->getThemeFile('body.css');
        $html = '';
        foreach ($files as $file) {
            if (!empty($this->config['hasCover']) && $file == 'cover.md') {
                continue;
            }
            $html .= $this->parseDown->parse(file_get_contents($file));
        }
        $html = $this->faParse($html, $withFA);
        return $this->getFirstFile('body-layout.twig', compact('baseCss', 'themeCss', 'html', 'withFA'));
    }

    private function getFirstFile($file, $variables = [])
    {
        $themeFile = empty($this->config['theme']) ? false : $this->getThemePath($file, $this->config['theme']);
        return $this->getThemeFile($file, $variables, !$themeFile || !file_exists(($themeFile)));
    }

    private function getThemeFile($file, $variables = [], $baseTheme = false)
    {
        if (!$baseTheme && empty($this->config['theme'])) {
            return '';
        }
        $filename = $this->getThemePath($file, !$baseTheme ? $this->config['theme'] : 'cli-press');
        return $this->templateManager->render($filename, $variables);
    }

    private function getThemePath($file, $theme)
    {
        return "$theme/$file";
    }

    private function getToc()
    {
        $baseToc = $this->getThemePath('toc.xsl', 'cli-press');
        $themeToc = $this->getThemePath('toc.xsl', !empty($this->config['theme']) ? $this->config['theme'] : 'cli-press');
        return __DIR__ . '/../themes/' . (file_exists(__DIR__ . "/../themes/$themeToc") ? $themeToc : $baseToc);
    }

    private function faParse($markup, &$count)
    {
        return preg_replace_callback('/(@|)\{f@([a-z0-9 -]+)\}/', function($matches) {
            if ($matches[1]) {
                return substr($matches[0], 1);
            }
            $matches = explode(' ', $matches[2]);
            $icon = array_shift($matches);
            $classes = '';
            foreach ($matches as $class) {
                if (preg_match('/^(lg|[2-5]x)|(rotate-(9|18|27)0)|flip-(horizontal|vertical)/', $class)) {
                    $classes .= ' fa-' . $class;
                }
            }
            return "<i class=\"fa fa-$icon$classes\"></i>";
        }, $markup, -1, $count);
    }
}
