<?php namespace ForsakenThreads\CliPress;

use mikehaertl\wkhtmlto\Pdf;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class Generate extends Command
{
    protected $config;

    /**
     * @var \ParsedownExtra
     */
    protected $parseDown;

    protected function configure()
    {
        $this
            ->setName('generate')
            ->setDescription('Generate PDF Documentation');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->parseDown = new \ParsedownExtra();
        $this->config = [
            'theme' => 'cli-press',
            'title' => 'Generated by CLI Press',
        ];

        if (file_exists('cli-press.json')) {
            $json = json_decode(file_get_contents('cli-press.json'), true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $this->config = array_merge($this->config, $json);
            }
        }

        if (empty($this->config['filename'])) {
            $this->config['filename'] = preg_replace('/[^\w\._-]/', '-', $this->config['title']);
        }

        if (!empty($this->config['theme'])) {
            if ($this->config['theme'] == 'cli-press' || !file_exists(dirname($this->getThemePath('file', $this->config['theme'])))) {
                $this->config['theme'] = false;
            }
        }

        $output->writeln('<comment>Starting the press</comment>');

        $pdf = new Pdf();

        $coverPageHtml = $this->generateCoverPageHtml();

        if ($coverPageHtml) {
            file_put_contents('cli-press_cover.html', $coverPageHtml);
            $pdf->addCover('cli-press_cover.html');
            $this->config['hasCover'] = true;
        }

        $pdf->setOptions([
            'header-html' => 'cli-press_header.html',
            'footer-html' => 'cli-press_footer.html',
        ]);

        $headerHtml = $this->generateHeaderHtml($this->config['title']);

        $bodyHtml = $this->generateBodyHtml(glob('*.md'));

        $footerHtml = $this->generateFooterHtml();

        file_put_contents('cli-press_header.html', $headerHtml);
        file_put_contents('cli-press_body.html', $bodyHtml);
        file_put_contents('cli-press_footer.html', $footerHtml);

        $pdf->addToc([
            'xsl-style-sheet' => $this->getToc()
        ]);

        $pdf->addPage('cli-press_body.html');

        if (!$pdf->saveAs($this->config['filename'] . '.pdf')) {
            $output->write('<fg=red>ERROR:</fg=red> ' . $pdf->getError());
        } else {
            $output->write("<info>Complete!</info>\n");
        }

        exec('rm cli-press_*.html');
    }

    private function generateCoverPageHtml() {
        if (!file_exists('cover.md')) {
            return '';
        }
        $coverContent = $this->parseDown->parse(file_get_contents('cover.md'));
        $coverContent = $this->faParse($coverContent, $withFA);
        $baseCss = $this->getThemeFile('cover.css', [], true);
        $themeCss = $this->getThemeFile('cover.css');
        $now = date('Y-m-d H:i:s');
        $cover = $this->getFirstFile('cover.phtml', compact('coverContent', 'now'));
        return $this->getFirstFile('cover-layout.phtml', compact('baseCss', 'themeCss', 'cover', 'withFA'));
    }

    private function generateHeaderHtml($title) {
        $baseCss = $this->getThemeFile('header.css', [], true);
        $themeCss = $this->getThemeFile('header.css');
        $header = $this->parseDown->parse($this->getFirstFile('header.phtml', compact('title')));
        $header = $this->faParse($header, $withFA);
        return $this->getFirstFile('header-layout.phtml', compact('baseCss', 'themeCss', 'header', 'withFA'));
    }

    private function generateFooterHtml() {
        $baseCss = $this->getThemeFile('footer.css', [], true);
        $themeCss = $this->getThemeFile('footer.css');
        $footer = $this->parseDown->parse($this->getFirstFile('footer.phtml'));
        $footer = $this->faParse($footer, $withFA);
        return $this->getFirstFile('footer-layout.phtml', compact('baseCss', 'themeCss', 'footer', 'withFA'));
    }

    private function generateBodyHtml($files) {
        $base = $this->getThemeFile('body.css', [], true);
        $theme = $this->getThemeFile('body.css');
        $html = '';
        foreach ($files as $file) {
            if (!empty($this->config['hasCover']) && $file == 'cover.md') {
                continue;
            }
            $html .= $this->parseDown->parse(file_get_contents($file));
        }
        $html = $this->faParse($html, $withFA);
        return $this->getFirstFile('body-layout.phtml', compact('base', 'theme', 'html', 'withFA'));
    }

    private function getFirstFile($file, $variables = [])
    {
        $themeFile = empty($this->config['theme']) ? false : $this->getThemePath($file, $this->config['theme']);
        return $this->getThemeFile($file, $variables, !$themeFile || !file_exists(($themeFile)));
    }

    private function getThemeFile($file, $variables = [], $baseTheme = false)
    {
        if (!$baseTheme && empty($this->config['theme'])) {
            return '';
        }
        $filename = $this->getThemePath($file, !$baseTheme ? $this->config['theme'] : 'cli-press');
        if (!file_exists($filename)) {
            return '';
        }
        extract($variables);
        ob_start();
        require $filename;
        $file = ob_get_contents();
        ob_end_clean();
        return $file;
    }

    private function getThemePath($file, $theme)
    {
        return __DIR__ . DIRECTORY_SEPARATOR . 'themes' . DIRECTORY_SEPARATOR . $theme . DIRECTORY_SEPARATOR . $file;
    }

    private function getToc()
    {
        $baseToc = $this->getThemePath('toc.xsl', 'cli-press');
        $themeToc = $this->getThemePath('toc.xsl', !empty($this->config['theme']) ? $this->config['theme'] : 'cli-press');
        return file_exists($themeToc)
            ? $themeToc
            : $baseToc;
    }

    private function faParse($markup, &$count)
    {
        return preg_replace_callback('/\{f@([a-z0-9 -]+)\}/', function($matches) {
            $matches = explode(' ', $matches[1]);
            $icon = array_shift($matches);
            $classes = '';
            foreach ($matches as $class) {
                if (preg_match('/^(lg|[2-5]x)|(rotate-(9|18|27)0)|flip-(horizontal|vertical)/', $class)) {
                    $classes .= ' fa-' . $class;
                }
            }
            return "<i class=\"fa fa-$icon$classes\"></i>";
        }, $markup, -1, $count);
    }
}
